# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: |
          **/bin/
          **/obj/
          
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:    
    - name: Download Build Artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifact
        path: .

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.x'

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
